FROM debian:trixie-slim

# Update and install needed utils
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl vim zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create symbolic link to ServerLog.txt
RUN mkdir /config /tshock && \
    touch /config/ServerLog.txt && \
    ln -s /config/ServerLog.txt /tshock/ServerLog.txt && \
    rm -rf /config

# fix for favorites.json error
RUN favorites_path="/root/My Games/Terraria" && mkdir -p "$favorites_path" && echo "{}" > "$favorites_path/favorites.json"

RUN cd /tmp && \
    curl -sL %%DOWNLOAD_URL%% --output tshock_release.zip && \
    unzip tshock_release.zip -d /tmp/tshock && \
    cd /tmp/tshock && \
    cd $(find . -name TerrariaServer.exe -printf '%h\n') && \
    mv ./* /tshock/ && \
    rm -R /tmp/* && \
    chmod +x /tshock/TerrariaServer.exe

COPY run-tshock.sh /tshock/run.sh

# Metadata
ARG VCS_REF
LABEL org.opencontainers.image.revision=$VCS_REF
LABEL org.opencontainers.image.source="https://github.com/beardedio/terraria"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.description="Tshock Dev Build Terraria Server - Build Num %%BUILD_NUMBER%%"
LABEL BUILD_NUM=%%BUILD_NUMBER%%

# Allow for external data
VOLUME ["/config", "/tshock/ServerPlugins"]

# Run the server
WORKDIR /tshock
ENTRYPOINT ["./run.sh"]
